
services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  producer-service:
    build:
      context: ./producer-service
    depends_on:
      - rabbitmq
    environment:
      SPRING_RABBITMQ_HOST: rabbitmq
    ports:
      - "8081:8080"
    command: ["java", "-jar", "/app/producer-service.jar"]

  consumer-service:
    build:
      context: ./consumer-service
    depends_on:
      - rabbitmq
    environment:
      SPRING_RABBITMQ_HOST: rabbitmq
    ports:
      - "8082:8080"
    command: ["java", "-jar", "/app/consumer-service.jar"]